// Mock data for testing the application
// Helper function to generate dates
const getRandomDate = (start, end) => {
  return new Date(start.getTime() + Math.random() * (end.getTime() - start.getTime())).toISOString();
};

export const mockIssues = [
  {
    id: "TKT001",
    title: "Broken Street Light",
    description: "Street light not working on Main Road",
    category: "Infrastructure",
    priority: "High",
    status: "In Progress",
    location: { lat: 23.3441, lng: 85.3096 },
    address: "Main Road, Ranchi",
    ward: "Ward 12",
    reportedBy: "John Doe",
    assignedTo: "Staff Member 1",
    createdAt: "2024-01-15T10:30:00Z",
    updatedAt: "2024-01-16T14:20:00Z",
    images: ["/broken-street-light.png"],
    timeline: [
      { status: "Reported", date: "2024-01-15T10:30:00Z", note: "Issue reported by citizen" },
      { status: "Assigned", date: "2024-01-15T15:45:00Z", note: "Assigned to maintenance team" },
      { status: "In Progress", date: "2024-01-16T09:00:00Z", note: "Work started on site" },
    ],
  },
  {
    id: "TKT002",
    title: "Pothole on Highway",
    description: "Large pothole causing traffic issues",
    category: "Roads",
    priority: "Medium",
    status: "Pending",
    location: { lat: 23.3521, lng: 85.324 },
    address: "NH-33, Ranchi",
    ward: "Ward 8",
    reportedBy: "Jane Smith",
    assignedTo: null,
    createdAt: "2024-01-14T08:15:00Z",
    updatedAt: "2024-01-14T08:15:00Z",
    images: ["/road-pothole.png"],
    timeline: [{ status: "Reported", date: "2024-01-14T08:15:00Z", note: "Issue reported by citizen" }],
  },
]

export const mockDemands = [
  {
    id: "DMD001",
    title: "New Park in Sector 5",
    description: "Request for a children's park in Sector 5 residential area",
    type: "infrastructure",
    status: "pending",
    votes: 45,
    location: { lat: 23.3398, lng: 85.3089 },
    address: "Sector 5, Ranchi",
    ward: "ward1",
    submittedBy: "Community Group",
    department: "public_works",
    submittedAt: "2024-01-10T12:00:00Z",
    images: ["/children-park-proposal.jpg"],
    estimatedCost: "₹15,00,000",
    supportingDocs: ["proposal.pdf", "site-plan.pdf"],
  },
  {
    id: "DMD002",
    title: "Better Bus Connectivity",
    description: "More frequent bus services to IT Park area",
    type: "services",
    status: "approved",
    votes: 78,
    location: { lat: 23.3445, lng: 85.3167 },
    address: "IT Park Road, Ranchi",
    ward: "ward2",
    submittedBy: "IT Employees Association",
    department: "public_works",
    submittedAt: "2024-01-08T09:30:00Z",
    images: ["/bus-stop-it-park.jpg"],
    estimatedCost: "₹8,00,000",
    supportingDocs: ["traffic-study.pdf"],
  },
  {
    id: "DMD003",
    title: "Street Light Installation",
    description: "Installation of LED street lights in Residential Block C",
    type: "utilities",
    status: "pending",
    votes: 56,
    location: { lat: 23.3512, lng: 85.3201 },
    address: "Block C, Residential Area",
    ward: "ward3",
    submittedBy: "Residents' Welfare Association",
    department: "utilities",
    submittedAt: "2024-01-15T14:20:00Z",
    images: ["/street-light-proposal.jpg"],
    estimatedCost: "₹5,00,000",
    supportingDocs: ["lighting-plan.pdf"],
  },
  {
    id: "DMD004",
    title: "Waste Management System",
    description: "Implementation of segregated waste collection system",
    type: "maintenance",
    status: "approved",
    votes: 92,
    location: { lat: 23.3445, lng: 85.3167 },
    address: "Multiple Locations",
    ward: "ward1",
    submittedBy: "Environmental Group",
    department: "sanitation",
    submittedAt: "2024-01-12T09:15:00Z",
    images: ["/waste-management.jpg"],
    estimatedCost: "₹12,00,000",
    supportingDocs: ["implementation-plan.pdf", "cost-analysis.pdf"],
  }
]

export const mockStaff = [
  {
    id: "STF001",
    name: "Rajesh Kumar",
    role: "Maintenance Engineer",
    department: "public_works",
    assignedTasks: 8,
    completedTasks: 5,
    avgResolutionTime: "2.5 days",
    performanceRating: 4.5,
    phone: "+91 9876543210",
    email: "rajesh@civic.gov",
    status: "active",
    joinedAt: "2023-06-15",
  },
  {
    id: "STF002",
    name: "Priya Singh",
    role: "Road Inspector",
    department: "public_works",
    assignedTasks: 12,
    completedTasks: 10,
    avgResolutionTime: "1.8 days",
    performanceRating: 4.8,
    phone: "+91 9876543211",
    email: "priya@civic.gov",
    status: "active",
    joinedAt: "2023-04-20",
  },
  {
    id: "STF003",
    name: "Amit Verma",
    role: "Sanitation Supervisor",
    department: "sanitation",
    assignedTasks: 15,
    completedTasks: 12,
    avgResolutionTime: "1.5 days",
    performanceRating: 4.6,
    phone: "+91 9876543212",
    email: "amit@civic.gov",
    status: "active",
    joinedAt: "2023-08-01",
  },
  {
    id: "STF004",
    name: "Meera Patel",
    role: "Utilities Inspector",
    department: "utilities",
    assignedTasks: 6,
    completedTasks: 4,
    avgResolutionTime: "2.2 days",
    performanceRating: 4.3,
    phone: "+91 9876543213",
    email: "meera@civic.gov",
    status: "active",
    joinedAt: "2023-09-10",
  },
  {
    id: "STF005",
    name: "Suresh Kumar",
    role: "Electrical Engineer",
    department: "utilities",
    assignedTasks: 10,
    completedTasks: 7,
    avgResolutionTime: "2.0 days",
    performanceRating: 4.4,
    phone: "+91 9876543214",
    email: "suresh@civic.gov",
    status: "active",
    joinedAt: "2023-07-05",
  }
]

export const mockAnalytics = {
  totalIssues: 156,
  resolvedIssues: 134,
  pendingIssues: 22,
  avgResolutionTime: "2.1 days",
  citizenSatisfaction: 87,
  topCategories: [
    { name: "Infrastructure", count: 45 },
    { name: "Roads", count: 38 },
    { name: "Water Supply", count: 32 },
    { name: "Waste Management", count: 28 },
    { name: "Others", count: 13 },
  ],
  monthlyTrends: [
    { month: "Jan", issues: 45, resolved: 42 },
    { month: "Feb", issues: 52, resolved: 48 },
    { month: "Mar", issues: 38, resolved: 35 },
    { month: "Apr", issues: 41, resolved: 39 },
    { month: "May", issues: 35, resolved: 33 },
    { month: "Jun", issues: 29, resolved: 27 },
  ],
}

export const wardBoundaries = [
  { id: 1, name: "Ward 1", center: [23.3441, 85.3096] },
  { id: 2, name: "Ward 2", center: [23.3521, 85.324] },
  { id: 3, name: "Ward 3", center: [23.3398, 85.3089] },
  { id: 4, name: "Ward 4", center: [23.3445, 85.3167] },
  { id: 5, name: "Ward 5", center: [23.3512, 85.3201] },
]
